id: IDB9287F8
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T19:55:09+00:00'
last_modified: '2022-06-08T12:51:55.124458+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN4666
  title: རྟེན་འབྲེལ་གྱི་རྣམ་བཞག་ལུང་རིགས་བང་མཛོད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '0160':
      image_group_id: I3CN4668
      title: ''
      total_pages: 68
      order: 1
      base_file: 0160.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
